Vehicle Management/Models/Home.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace Vehicle_Management.Models
{
	public class VehicleView
	{
		public int Id { get; set; }
		[Required]
		public string? RegistrationNumber { get; set; }
		public string? ManufactureCompany { get; set; }
		public string? VehicleModel { get; set; }
		public int EngineCapacity { get; set; }
		public int ManufacturedYear { get; set; }
		public DateTime PurchasedOn { get; set; }
		public string? Color { get; set; }
		public string? EngineNumber { get; set; }
		public string? ChasisNumber { get; set; }
		public int PassengerCapacity { get; set; }
		public string? Fuel { get; set; }
		public bool IsAvailable { get; set; }
        public DateTime CreatedDate { get; set; }
        public String? CreatedById { get; set; }
        public UserManager? User { get; set; }
    }
}

Vehicle Management/Models/RegisterUser.cs
using System.ComponentModel.DataAnnotations;

namespace Vehicle_Management.Models
{
    public class RegisterUser
    {
        public string? Name { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string? Email { get; set; }

        [Required]
        public string? Role { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string? Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string? ConfirmPassword { get; set; }
    }
}

Vehicle Management/Controllers/DriverController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Vehicle_Management.Hubs;
using Vehicle_Management.Models;
using Vehicle_Management.Services;

namespace Vehicle_Management.Controllers
{
	public class DriverController : Controller
	{
		private readonly UserManager<UserManager> _userManager;
		private readonly ILogger<HomeController> _logger;
		private readonly ApplicationDbContext _dbContext;
        private readonly NotificationHub _notification;
        private readonly NotificationService _notificationService;

        public DriverController(ILogger<HomeController> logger, ApplicationDbContext dbContext, UserManager<UserManager> userManager, NotificationHub notification, NotificationService notificationService)
		{
			_userManager = userManager;
			_logger = logger;
			_dbContext = dbContext;
			_notification = notification;
			_notificationService = notificationService;
		}

		// View Tasks
		public async Task<ActionResult> ViewTask(BaseViewModel model)
		{
			var currentUser = await _userManager.GetUserAsync(User);
			if (currentUser != null)
			{
				var request = _dbContext.Requests.ToList();
				if (request != null)
				{
					model.UserRequests = request.Where(r => r.DriverUserId == currentUser.Id).Select(r => new UserRequest
					{
						Id = r.Id,
						RequestedDate = r.RequestedDate,
						PickupPoint = r.PickupPoint,
						PickupPointLandmark = r.PickupPointLandmark,
						DropPoint = r.DropPoint,
						DropPointLandmark = r.DropPointLandmark,
						CreatedDate = r.CreatedDate,
						IsApproved = r.IsApproved,
						IsUnapproved = r.IsUnapproved,
						IsCompleted = r.IsCompleted,
						UserId = r.UserId,
					}).ToList();
				}
				model.Notifications = _notificationService.getDriverNotification(currentUser.Id);
			}
            return View(model);
		}

        //Mark Task Complete
        [HttpGet]
        public async Task<IActionResult> CompletedTask(int id, RequestHistory newRequestHistory)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var getRequest = _dbContext.Requests.Include(r => r.RequestStatus).FirstOrDefault(r => r.Id == id);
            if (getRequest is null)
            {
                return NotFound();
            }
            getRequest.IsCompleted = true;
			getRequest.SetRequestStatus(_dbContext,"Completed");
            _dbContext.SaveChanges();

			newRequestHistory = new RequestHistory();
			newRequestHistory.CreatedDate = DateTime.Now;
			newRequestHistory.RequestId = getRequest.Id;
			newRequestHistory.RequestStatusId = getRequest.RequestStatus.Id;
			newRequestHistory.CreatedById = currentUser.Id;
			_dbContext.Add(newRequestHistory);
			_dbContext.SaveChanges();

			await _notification.SendNotificationToAdmins(currentUser.Id, getRequest.Id, "RequestCompleted");
            return RedirectToAction("ViewTask");
        }
    }
}

Vehicle Management/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Vehicle_Management.Models;
using Vehicle_Management.Hubs;
using Microsoft.AspNetCore.SignalR;
using Vehicle_Management.Data;
using Vehicle_Management.Services;
using Microsoft.EntityFrameworkCore;

namespace Vehicle_Management.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<UserManager> _userManager;
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _dbContext;
        private readonly NotificationHub _notification;
        private readonly NotificationService _notificationService;

        public UserController(ILogger<HomeController> logger, ApplicationDbContext dbContext, UserManager<UserManager> userManager, NotificationHub notification, NotificationService notificationService)
        {
            _userManager = userManager;
            _logger = logger;
            _dbContext = dbContext;
            _notification = notification;
            _notificationService = notificationService;
        }

        [HttpGet]
        public async Task<IActionResult> Home(BaseViewModel model)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null)
            {
            var request = _dbContext.Requests.ToList();
                if (request != null)
                {
                    model.UserRequests = request.Where(r => r.UserId == currentUser.Id).Select(r => new UserRequest
                    {
                        Id = r.Id,
                        RequestedDate = r.RequestedDate,
                        PickupPoint = r.PickupPoint,
                        PickupPointLandmark = r.PickupPointLandmark,
                        DropPoint = r.DropPoint,
                        DropPointLandmark = r.DropPointLandmark,
                        CreatedDate = r.CreatedDate,
                        IsApproved = r.IsApproved,
                        IsUnapproved = r.IsUnapproved,
                        IsCompleted = r.IsCompleted,
                        IsCancelled = r.IsCancelled,
                        UserId = r.UserId,
                    }).ToList();
                    model.Notifications = _notificationService.getUserNotification(currentUser.Id);
                    model.UserRequest = new UserRequest
                    {
                        PickupPoint = TempData["PickupPoint"]?.ToString() ?? "",
                        DropPoint = TempData["DropPoint"]?.ToString() ?? "",
                        PickupPointLandmark = TempData["PickupPointLandmark"]?.ToString() ?? "",
                        DropPointLandmark = TempData["DropPointLandmark"]?.ToString() ?? "",
                        RequestedDate = TempData["RequestedDate"] as DateTime? ?? DateTime.MinValue,
                        Message = TempData["RequestMessage"]?.ToString() ?? ""
                    };
                }
            }
            return View(model);
		}
		[HttpPost]
        public async Task<IActionResult> Home(BaseViewModel model, Request newRequest, RequestMessage newRequestMessage, RequestHistory newRequestHistory)
        {
			var currentUser = await _userManager.GetUserAsync(User);

            newRequest.PickupPoint = model.UserRequest.PickupPoint;
            newRequest.PickupPointLandmark = model.UserRequest.PickupPointLandmark;
            newRequest.DropPoint = model.UserRequest.DropPoint;
            newRequest.DropPointLandmark = model.UserRequest.DropPointLandmark;
            newRequest.RequestedDate = model.UserRequest.RequestedDate;
            newRequest.UserId = currentUser.Id;
            newRequest.CreatedbyId = currentUser.Id;
            newRequest.CreatedDate = DateTime.Now;
			newRequest.SetRequestStatus(_dbContext, "Requested");
			_dbContext.Add(newRequest);
			_dbContext.SaveChanges();
			int newRequestId = newRequest.Id;

            newRequestMessage.Message = model.UserRequest.Message;
            newRequestMessage.CreatedDate = DateTime.Now;
            newRequestMessage.RequestId = newRequestId;
            newRequestMessage.CreatedById = currentUser.Id;
            _dbContext.Add(newRequestMessage);

            newRequestHistory.CreatedDate = DateTime.Now;
            newRequestHistory.RequestId = newRequestId;
            newRequestHistory.RequestStatusId = newRequest.RequestStatusId;
            newRequestHistory.CreatedById = currentUser.Id;
			_dbContext.Add(newRequestHistory);
			_dbContext.SaveChanges();

            TempData["message"] = "New Vehicle Request Created";
			if (currentUser != null)
            {
               await _notification.SendNotificationToAdmins(currentUser.Id, newRequestId, "NeedsApproval");
            }

            return RedirectToAction("Home");

        }

        [HttpGet]
        public async Task<IActionResult> CancelRequest(int id, RequestHistory newRequestHistory)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null) 
            {
                var getRequest = _dbContext.Requests.Include(r => r.RequestStatus).AsEnumerable().FirstOrDefault(r => r.Id == id && r.CreatedbyId == currentUser.Id);
                if (getRequest is null)
                {
                    return NotFound();
                }
                getRequest.IsCancelled = true;
                getRequest.IsCompleted = true;
                getRequest.SetRequestStatus(_dbContext, "Cancelled");

                var notification = _dbContext.Notifications.Include(n => n.NotificationType).AsEnumerable().FirstOrDefault(n => n.RequestId == getRequest.Id && n.IsOfType("NeedsApproval"));
                if (notification != null)
                {
                    _dbContext.Remove(notification);
                    _dbContext.SaveChanges();
                }

                newRequestHistory = new RequestHistory();
                newRequestHistory.CreatedDate = DateTime.Now;
                newRequestHistory.RequestId = getRequest.Id;
                newRequestHistory.RequestStatusId = getRequest.RequestStatus.Id;
                newRequestHistory.CreatedById = currentUser.Id;
                _dbContext.Add(newRequestHistory);
                _dbContext.SaveChanges();

                return RedirectToAction("Home");
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> EditRequest(int id, BaseViewModel model) 
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null)
            {
                var getRequest = _dbContext.Requests.Include(r => r.RequestStatus).AsEnumerable().FirstOrDefault(r => r.Id == id && r.CreatedbyId == currentUser.Id && r.HasStatus("Requested"));
                if (getRequest is null)
                {
                    return NotFound();
                }
                var message = _dbContext.RequestMessages.FirstOrDefault(rm => rm.RequestId == getRequest.Id);
                model.UserRequest = new UserRequest
                {
                    PickupPoint = getRequest.PickupPoint,
                    DropPoint = getRequest.DropPoint,
                    PickupPointLandmark = getRequest.PickupPointLandmark,
                    DropPointLandmark = getRequest.DropPointLandmark,
                    RequestedDate = getRequest.RequestedDate,
                    Message = message.Message
                };
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditRequest(BaseViewModel model, int id)
        {
			var currentUser = await _userManager.GetUserAsync(User);
			if (currentUser != null)
			{
				var getRequest = _dbContext.Requests.Include(r => r.RequestStatus).AsEnumerable().FirstOrDefault(r => r.Id == id && r.CreatedbyId == currentUser.Id && r.HasStatus("Requested"));
				if (getRequest is null)
				{
					return NotFound();
				}
				var message = _dbContext.RequestMessages.FirstOrDefault(rm => rm.RequestId == getRequest.Id);
				getRequest.PickupPoint = model.UserRequest.PickupPoint;
                getRequest.DropPoint = model.UserRequest.DropPoint;
                getRequest.PickupPointLandmark = model.UserRequest.PickupPointLandmark;
                getRequest.DropPointLandmark = model.UserRequest.DropPointLandmark;
                getRequest.RequestedDate = model.UserRequest.RequestedDate;
                message.Message = model.UserRequest.Message;
                _dbContext.SaveChanges();
				return RedirectToAction("Home");
			}
			return NotFound();
			
        }

	}
}

Vehicle Management/Views/Home/AddVehicle.cshtml
@model Vehicle_Management.Models.BaseViewModel
@{
    ViewData["Title"] = "AddVehicle";
}

@if (User.IsInRole("Admin"))
{
	<div class="container">
		<div class="row">
			<div class="col-md-5">
				<h1>New Vehicle Registration</h1>
				<form asp-controller="Home" asp-action="AddVehicle" method="post">
					<div class="form-group pb-3">
						<label asp-for="Vehicle.RegistrationNumber">Registration Number</label>
						<input asp-for="Vehicle.RegistrationNumber" type="text" class="form-control" id="registration-number">
						<span asp-validation-for="Vehicle.RegistrationNumber" class="text-danger"></span>
					</div>
					<div class="form-group pb-3">
						<label asp-for="Vehicle.ManufactureCompany">Manufacture Company</label>
						<input asp-for="Vehicle.ManufactureCompany" type="text" class="form-control" id="manufacture-company">
						<span asp-validation-for="Vehicle.ManufactureCompany" class="text-danger"></span>
					</div>
					<div class="form-group pb-3">
						<label asp-for="Vehicle.VehicleModel">Vehicle Model</label>
						<input asp-for="Vehicle.VehicleModel" type="text" class="form-control" id="vehicle-model">
						<span asp-validation-for="Vehicle.VehicleModel" class="text-danger"></span>
					</div>
					<div class="form-group pb-3">
						<label asp-for="Vehicle.EngineCapacity">Engine Capacity(cc)</label>
						<input asp-for="Vehicle.EngineCapacity" type="number" class="form-control" id="engine-capacity">
						<span asp-validation-for="Vehicle.EngineCapacity" class="text-danger"></span>
					</div>
					<div class="form-group pb-3">
						<label asp-for="Vehicle.ManufacturedYear">Manufactured Year</label>
						<input asp-for="Vehicle.ManufacturedYear" type="number" class="form-control" id="manufactured-year">
						<span asp-validation-for="Vehicle.ManufacturedYear" class="text-danger"></span>
					</div>
					<div class="form-group pb-3">
						<label asp-for="Vehicle.PurchasedOn">Purchased On</label>
						<input asp-for="Vehicle.PurchasedOn" type="date" class="form-control" id="purchased-on" name="PurchasedOn" value="2000-01-15">
						<span asp-validation-for="Vehicle.PurchasedOn" class="text-danger"></span>
					</div>
					<div class="form-group pb-3">
						<label asp-for="Vehicle.Color">Color</label>
						<input asp-for="Vehicle.Color" type="text" class="form-control" id="color">
						<span asp-validation-for="Vehicle.Color" class="text-danger"></span>
					</div>
					<div class="form-group pb-3">
						<label asp-for="Vehicle.EngineNumber">Engine Number</label>
						<input asp-for="Vehicle.EngineNumber" type="text" class="form-control" id="engine-number">
						<span asp-validation-for="Vehicle.EngineNumber" class="text-danger"></span>
					</div>
					<div class="form-group pb-3">
						<label asp-for="Vehicle.ChasisNumber">Chasis Number</label>
						<input asp-for="Vehicle.ChasisNumber" type="text" class="form-control" id="chasis-number">
						<span asp-validation-for="Vehicle.ChasisNumber" class="text-danger"></span>
					</div>
					<div class="form-group pb-3">
						<label asp-for="Vehicle.PassengerCapacity">Passenger Capacity</label>
						<input asp-for="Vehicle.PassengerCapacity" type="number" class="form-control" id="passenger-capacity">
						<span asp-validation-for="Vehicle.PassengerCapacity" class="text-danger"></span>
					</div>
					<div class="form-group pb-4">
						<label asp-for="Vehicle.Fuel">Fuel</label>
						<select asp-for="Vehicle.Fuel" class="form-control" id="fuel">
							<option value="Diesel">Diesel</option>
							<option value="Petrol">Petrol</option>
						</select>
						<span asp-validation-for="Vehicle.Fuel" class="text-danger"></span>
					</div>
					<button type="submit" class="btn btn-primary">Add</button>
				</form>
			</div>
		</div>
	</div>
}
else
{
    <h1>Access Denied</h1>
}

Vehicle Management/Views/Home/AllNotifications.cshtml
@model Vehicle_Management.Models.BaseViewModel
@inject UserManager<UserManager> UserManager
@{
    ViewData["Title"] = "All Notifications";
}

@if (Model != null && Model.AllNotifications != null)
{
    <h1 class="pt-2 ml-4">Notifications</h1>
    @foreach (var notification in Model.AllNotifications)
    {
        @if (notification.NotificationType == "NeedsApproval")
        {
            <a class="dropdown-item d-flex align-items-center" asp-controller="Home" asp-action="ApproveRequest" asp-route-id="@notification.RequestId">
                <div class="mr-3">
                    <div class="icon-circle bg-primary">
                        <i class="fas fa-file-alt text-white"></i>
                    </div>
                </div>
                <div>
                    <div class="small text-gray-500">@notification.Date</div>
                    @{
                        var notificationSender = await UserManager.FindByIdAsync(notification.CreatedById);
                    }
                    <span class="font-weight-bold">Request by @notificationSender.Name needs approval</span>
                </div>
            </a>
        }

        @if (notification.NotificationType == "RequestCompleted")
        {
            <a class="dropdown-item d-flex align-items-center" asp-controller="Home" asp-action="ViewRequests">
                <div class="mr-3">
                    <div class="icon-circle bg-primary">
                        <i class="fas fa-file-alt text-white"></i>
                    </div>
                </div>
                <div>
                    <div class="small text-gray-500">@notification.Date</div>
                    @{
                        var notificationSender = await UserManager.FindByIdAsync(notification.CreatedById);
                    }
                    <span class="font-weight-bold">@notificationSender.Name has completed a request.</span>
                </div>
            </a>
        }

        @if (notification.NotificationType == "IsApproved")
        {
            <a class="dropdown-item d-flex align-items-center" asp-controller="User" asp-action="Home">
                <div class="mr-3">
                    <div class="icon-circle bg-primary">
                        <i class="fas fa-file-alt text-white"></i>
                    </div>
                </div>
                <div>
                    <div class="small text-gray-500">@notification.Date</div>
                    @{
                        var notificationSender = await UserManager.FindByIdAsync(notification.CreatedById);
                    }
                    <span class="font-weight-bold">@notificationSender.Name has approved your request.</span>
                </div>
            </a>
        }

        @if (notification.NotificationType == "IsPending")
        {
            <a class="dropdown-item d-flex align-items-center" asp-controller="Driver" asp-action="ViewTask">
                <div class="mr-3">
                    <div class="icon-circle bg-primary">
                        <i class="fas fa-file-alt text-white"></i>
                    </div>
                </div>
                <div>
                    <div class="small text-gray-500">@notification.Date</div>
                    <span class="font-weight-bold">A new request is pending.</span>
                </div>
            </a>
        }
    }
}

Vehicle Management/Views/Home/AllUsers.cshtml
@model Vehicle_Management.Models.BaseViewModel
@{
    ViewData["Title"] = "All Users";
}
<!-- Page Heading -->
@if (User.IsInRole("Admin"))
{
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col">
                    <h4 class="m-0 font-weight-bold text-primary">Users</h4>
                </div>
                <ul class="nav nav-tabs nav-sm-justified" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="active-tab" data-bs-toggle="tab" data-bs-target="#active" type="button" role="tab" aria-controls="active" aria-selected="true"><h6 class="m-0 font-weight-bold text-primary">Active Users</h6></button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="disabled-tab" data-bs-toggle="tab" data-bs-target="#disabled" type="button" role="tab" aria-controls="disabled" aria-selected="false"><h6 class="m-0 font-weight-bold text-primary">Disabled Users</h6></button>
                    </li>
                </ul>
            </div>
        </div>
        <div class="tab-content">
            <div class="tab-pane fade show active" id="active" role="tabpanel" aria-labelledby="active-tab">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable1" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th class="text-center">Name</th>
                                    <th class="text-center">Email</th>
                                    <th class="text-center">Role</th>
                                    <th class="text-center">Total Requests</th>
                                    <th>Disable</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.UserDetails != null)
                                {
                                    @foreach (var userDetail in Model.UserDetails)
                                    {
                                        @if (!userDetail.IsDisabled)
                                        {
                                            <tr>
                                                <td class="text-center">@userDetail.Name</td>
                                                <td class="text-center">@userDetail.Email</td>
                                                <td class="text-center">@userDetail.Role</td>
                                                <td class="text-center">@userDetail.TotalRequests</td>
                                                <td class="text-center">
                                                    <a href="" onclick="disableConfirmation(event, '@userDetail.Id');" data-bs-toggle="modal" data-bs-target="#disableConfirmationModal"><i class="bi bi-shield-slash-fill" title="Disable User" style="font-size: 22px; color: red;"></i></a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="disabled" role="tabpanel" aria-labelledby="disabled-tab">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable2" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th class="text-center">Name</th>
                                    <th class="text-center">Email</th>
                                    <th class="text-center">Role</th>
                                    <th class="text-center">Total Requests</th>
                                    <th>Enable</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.UserDetails != null)
                                {
                                    @foreach (var userDetail in Model.UserDetails)
                                    {
                                        @if (userDetail.IsDisabled)
                                        {
                                            <tr>
                                                <td class="text-center">@userDetail.Name</td>
                                                <td class="text-center">@userDetail.Email</td>
                                                <td class="text-center">@userDetail.Role</td>
                                                <td class="text-center">@userDetail.TotalRequests</td>
                                                <td class="text-center">
                                                    <a href="" onclick="enableConfirmation(event, '@userDetail.Id');" data-bs-toggle="modal" data-bs-target="#enableConfirmationModal"><i class="bi bi-shield-fill-check" title="Enable User" style="font-size: 22px; color: black;"></i></a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Disable Popup Modal -->
    <div class="modal fade" id="disableConfirmationModal" tabindex="-1" aria-labelledby="disableConfirmationModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="disableConfirmationModalLabel">Disable User</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to disable this user?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a asp-controller="Home" asp-action="DisableUser" id="disableButton" class="btn btn-danger">Disable</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Enable Popup Modal -->
    <div class="modal fade" id="enableConfirmationModal" tabindex="-1" aria-labelledby="enableConfirmationModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="enableConfirmationModalLabel">Enable User</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to enable this user?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                    <a asp-controller="Home" asp-action="EnableUser" id="enableButton" class="btn btn-secondary">Enable</a>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('#dataTable1').dataTable({
                "paging": true,
                "searching": true
            });
            $('#dataTable2').dataTable({
                "paging": true,
                "searching": true
            });
        });
    </script>

    <script>
        // Function to search table rows
        function searchTable() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }

        function disableConfirmation(event, id) {
            event.preventDefault();
            $('#disableButton').attr('href', '/Home/DisableUser/' + id);
        }

        function enableConfirmation(event, id) {
            event.preventDefault();
            $('#enableButton').attr('href', '/Home/EnableUser/' + id);
        }
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/js/bootstrap.bundle.min.js"></script>
}